# Generated by Django 4.0.3 on 2023-09-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_alter_lead_activity_actual_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_converted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
