# Generated by Django 4.0.3 on 2023-09-06 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0012_lead_is_converted_lead_is_rejected_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=50)),
                ('contact_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('conversation_date', models.DateField()),
                ('renewal_date', models.DateField()),
                ('start_date', models.DateField()),
                ('subscription_used_date', models.DateField(max_length=10)),
                ('payment_cycle', models.CharField(max_length=10)),
                ('gst_no', models.CharField(max_length=50)),
                ('lead_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
            ],
        ),
    ]
