# Generated by Django 4.0.3 on 2023-09-25 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_created_at_customer_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_communication',
            name='proablity',
        ),
    ]
